version: '3.9'

services:
  nginx:
    image: nginx:docker
    restart: always
    ports:
      - "443:443"
      - "1111:1111"
      - "5555:5555"
    links:
      - nexus-repo

  nexus-repo:
    image: sonatype/nexus3:3.62.0
    restart: always
    volumes:
      - 'nexus3-data:/nexus-data'

volumes:
  nexus3-data: