version: '3.9'

services:
  nginx-nexusproxy:
    image: nginx-nexusproxy
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    links:
      - nexus-repo
    command: [ nginx, '-g', 'daemon off;' ]

  nexus-repo:
    image: sonatype/nexus3:3.62.0
    volumes:
      - 'nexus3-data:/nexus-data'

volumes:
  nexus3-data: